name: Move Files on gh-pages

on:
  workflow_run:
    workflows: ["Unity WebGL Automatic Build"]
    types:
      - completed

jobs:
  move:
    name: Test Move WebGL Build to Location of .nojekyll
    runs-on: ubuntu-latest

    steps:
      # Checkout the gh-pages branch
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      # Debug step: List all files to understand the structure
      - name: List all files before move
        run: |
          echo "Listing all files before moving:"
          sudo ls -R
      
      # Find and move files to the root folder
      - name: Find and move files to root
        run: |
          sudo mv $(find . -type d -name 'Build') ./
          sudo mv $(find . -type f -name 'index.html') ./
      
      # Commit and Push changes using git-auto-commit-action
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Move Build folder and index.html to root"
          branch: gh-pages
          
